
# ============================================================
# Veridian Corp — IT Support Agent — Knowledge Base
# Week of Monday 21 Sep 2026 – Friday 25 Sep 2026
# ============================================================

KNOWLEDGE_BASE = {
    "KB-01": {
        "title": "Password Reset",
        "content": (
            "Employees can reset their own password via the self-service portal at any time. "
            "If locked out after 5 failed attempts, contact IT to unlock the account manually. "
            "No approval required."
        )
    },
    "KB-02": {
        "title": "VPN Access",
        "content": (
            "VPN access is granted automatically to all full-time employees. "
            "Contractors require manager approval submitted via the access request form. "
            "VPN credentials expire every 90 days and must be renewed by the employee."
        )
    },
    "KB-03": {
        "title": "Laptop Replacement",
        "content": (
            "Laptops are eligible for replacement after 3 years of service, or earlier in case of "
            "verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
        )
    },
    "KB-04": {
        "title": "Software Installation Requests",
        "content": (
            "Standard software (listed in the approved catalog) can be self-installed. "
            "Non-catalog software requires IT Security review, which takes 3–5 business days."
        )
    },
    "KB-05": {
        "title": "Printer Troubleshooting",
        "content": (
            "For printer issues, first check the printer queue and restart the print spooler. "
            "If the issue persists after restart, log a ticket with the printer's asset tag."
        )
    },
    "KB-06": {
        "title": "Email Mailbox Quota",
        "content": (
            "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. "
            "Quota increases beyond 25GB require manager approval and are capped at 50GB."
        )
    },
    "KB-07": {
        "title": "Guest Wi-Fi Access",
        "content": (
            "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee "
            "from the front-desk kiosk. No IT ticket required."
        )
    },
    "KB-08": {
        "title": "Expense Software Access",
        "content": (
            "Access to the expense management tool is granted by Finance, not IT. "
            "IT can only assist with login/technical issues once an account already exists."
        )
    },
    "KB-09": {
        "title": "Security Incident Reporting",
        "content": (
            "Any suspected phishing email, malware, or unauthorized access attempt must be reported "
            "to security@veridian-corp.example immediately and should not be forwarded to other employees."
        )
    },
    "KB-10": {
        "title": "Work-From-Home Equipment",
        "content": (
            "Employees working remotely more than 3 days/week are eligible for a one-time home office "
            "equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — "
            "IT only handles the equipment shipping request once approved."
        )
    },
    "ASSET-POLICY": {
        "title": "Asset Management Policy",
        "content": (
            "All company-issued hardware, including laptops and monitors, follows a standard 4-year "
            "refresh cycle from date of issue. Early replacement outside this cycle requires Finance "
            "sign-off in addition to IT approval. (Issued by Finance & Assets, last updated Q2 2026)"
        )
    }
}

EMPLOYEE_REQUESTS = [
    {
        "id": "REQ-01",
        "employee": "Aditi Sharma",
        "email": "aditi.sharma@veridian-corp.example",
        "date": "Mon 21 Sep",
        "request": "My laptop won't turn on at all, it's completely dead, had it about 3.5 years now.",
        "status": "Not started",
        "category": "Hardware",
        "priority": "High"
    },
    {
        "id": "REQ-02",
        "employee": "Vikram Chawla",
        "email": "vikram.chawla@veridian-corp.example",
        "date": "Mon 21 Sep",
        "request": "Can I get Wi-Fi access for a guest visiting our office tomorrow?",
        "status": "Not started",
        "category": "Network",
        "priority": "Low"
    },
    {
        "id": "REQ-03",
        "employee": "Karan Mehta",
        "email": "karan.mehta@veridian-corp.example",
        "date": "Mon 21 Sep",
        "request": "I'm locked out of my account, tried my password 6 times.",
        "status": "In Progress",
        "category": "Access",
        "priority": "High"
    },
    {
        "id": "REQ-04",
        "employee": "Ritu Bhatia",
        "email": "ritu.bhatia@veridian-corp.example",
        "date": "Tue 22 Sep",
        "request": "Need approval to install a data-analysis tool that's not in the software catalog.",
        "status": "Waiting on Security review",
        "category": "Software",
        "priority": "Medium"
    },
    {
        "id": "REQ-05",
        "employee": "Sanjay Oberoi",
        "email": "sanjay.oberoi@veridian-corp.example",
        "date": "Tue 22 Sep",
        "request": "My VPN stopped working this morning, says credentials expired.",
        "status": "Not started",
        "category": "Network",
        "priority": "High"
    },
    {
        "id": "REQ-06",
        "employee": "Meera Iyer",
        "email": "meera.iyer@veridian-corp.example",
        "date": "Tue 22 Sep",
        "request": "Printer on the 3rd floor keeps showing 'paper jam' even though there's no jam.",
        "status": "Investigating",
        "category": "Hardware",
        "priority": "Medium"
    },
    {
        "id": "REQ-07",
        "employee": "Farhan Ali",
        "email": "farhan.ali@veridian-corp.example",
        "date": "Wed 23 Sep",
        "request": "I've started working from home 4 days a week, how do I get a monitor?",
        "status": "Not started",
        "category": "Equipment",
        "priority": "Low"
    },
    {
        "id": "REQ-08",
        "employee": "Ananya Reddy",
        "email": "ananya.reddy@veridian-corp.example",
        "date": "Wed 23 Sep",
        "request": "I think I got a phishing email asking for my login — forwarding it to a few teammates to check.",
        "status": "Escalated to Security",
        "category": "Security",
        "priority": "Critical"
    },
    {
        "id": "REQ-09",
        "employee": "Rohit Desai",
        "email": "rohit.desai@veridian-corp.example",
        "date": "Wed 23 Sep",
        "request": "My mailbox is full and I can't send emails.",
        "status": "Not started",
        "category": "Email",
        "priority": "High"
    },
    {
        "id": "REQ-10",
        "employee": "Kavya Pillai",
        "email": "kavya.pillai@veridian-corp.example",
        "date": "Wed 23 Sep",
        "request": "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.",
        "status": "Not started",
        "category": "Access",
        "priority": "High"
    },
    {
        "id": "REQ-11",
        "employee": "Nikhil Bansal",
        "email": "nikhil.bansal@veridian-corp.example",
        "date": "Thu 24 Sep",
        "request": "New contractor joining my team next week, they'll need VPN access.",
        "status": "Not started",
        "category": "Access",
        "priority": "Medium"
    },
    {
        "id": "REQ-12",
        "employee": "Sneha Kulkarni",
        "email": "sneha.kulkarni@veridian-corp.example",
        "date": "Thu 24 Sep",
        "request": "I can't log into the expense tool, keeps saying invalid credentials.",
        "status": "Waiting on employee response",
        "category": "Software",
        "priority": "Medium"
    },
    {
        "id": "REQ-13",
        "employee": "Aman Gupta",
        "email": "aman.gupta@veridian-corp.example",
        "date": "Thu 24 Sep",
        "request": "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.",
        "status": "Not started",
        "category": "Hardware",
        "priority": "Medium"
    },
    {
        "id": "REQ-14",
        "employee": "Tanya Chopra",
        "email": "tanya.chopra@veridian-corp.example",
        "date": "Fri 25 Sep",
        "request": "Requesting approval to install a browser extension for productivity tracking.",
        "status": "Not started",
        "category": "Software",
        "priority": "Low"
    },
    {
        "id": "REQ-15",
        "employee": "Rahul Menon",
        "email": "rahul.menon@veridian-corp.example",
        "date": "Fri 25 Sep",
        "request": "hey can you help, its not working",
        "status": "Not started",
        "category": "Unknown",
        "priority": "Low"
    }
]

TICKET_QUEUE = [
    {
        "id": "TK-1042",
        "employee": "R. Verma",
        "issue": "VPN credential expired",
        "status": "Resolved",
        "closed": True,
        "category": "Network"
    },
    {
        "id": "TK-1043",
        "employee": "S. Iyer",
        "issue": "Laptop replacement (3.2 yrs old)",
        "status": "Approved — pending fulfillment",
        "closed": False,
        "category": "Hardware"
    },
    {
        "id": "TK-1044",
        "employee": "A. Khan",
        "issue": "Non-catalog software request",
        "status": "Pending Security review",
        "closed": False,
        "category": "Software"
    },
    {
        "id": "TK-1045",
        "employee": "P. Joshi",
        "issue": "Mailbox quota increase",
        "status": "Approved at 35GB",
        "closed": True,
        "category": "Email"
    },
    {
        "id": "TK-1046",
        "employee": "M. Das",
        "issue": "Printer paper jam, floor 2",
        "status": "Resolved",
        "closed": True,
        "category": "Hardware"
    },
    {
        "id": "TK-1047",
        "employee": "K. Singh",
        "issue": "Home office equipment request",
        "status": "Pending Finance",
        "closed": False,
        "category": "Equipment"
    },
    {
        "id": "TK-1048",
        "employee": "T. Rao",
        "issue": "Phishing email reported",
        "status": "Escalated to Security — under investigation",
        "closed": False,
        "category": "Security"
    },
    {
        "id": "TK-1049",
        "employee": "V. Nambiar",
        "issue": "Password reset",
        "status": "Resolved",
        "closed": True,
        "category": "Access"
    },
    {
        "id": "TK-1050",
        "employee": "J. Fernandes",
        "issue": "Admin access request",
        "status": "Rejected — no business justification provided",
        "closed": True,
        "category": "Access"
    },
    {
        "id": "TK-1051",
        "employee": "L. Menon",
        "issue": "Guest Wi-Fi issued",
        "status": "Resolved",
        "closed": True,
        "category": "Network"
    }
]


def build_system_prompt():
    """Build the comprehensive system prompt for the AI agent following the PDF Architecture Decision Workflow."""
    kb_text = "\n".join([
        f"[{kid}] {v['title']}: {v['content']}"
        for kid, v in KNOWLEDGE_BASE.items()
    ])
    ticket_history = "\n".join([
        f"[{t['id']}] {t['employee']} - {t['issue']} (Status: {t['status']}, Closed: {t['closed']}, Category: {t['category']})"
        for t in TICKET_QUEUE
    ])
    return f"""You are ARIA (Automated Resolution & IT Assistant), the internal IT Support Agent for Veridian Corp.
Your role is to triage, resolve, or route IT support requests based strictly on company policy and ticket precedents.

DECISION WORKFLOW ARCHITECTURE:
For every user issue or employee request, evaluate both the Knowledge Base and Ticket Queue precedents to make one of two decisions:

1. RESOLVE DIRECTLY:
   - Use when the issue can be solved immediately via self-service or standard user steps (e.g. self-service password reset portal, 24-hr guest Wi-Fi kiosk, print spooler restart, archiving full email mailbox).

2. ROUTE TO HUMAN:
   - Route/Escalate when human approval, security investigation, or specialized handling is required:
     * Phishing / Security alerts: Route immediately to IT Security (security@veridian-corp.example). NEVER allow forwarding.
     * Admin access requests: Reject without proper business justification (precedent TK-1050), or route to IT Security/Manager.
     * Non-catalog software: Route to IT Security review (3–5 business days).
     * Contractor VPN / WFH Monitor / Mailbox Quota > 25GB / Early Laptop Replacement (< 4 years): Route to Manager / Finance / Procurement.

=== KNOWLEDGE BASE ===
{kb_text}

=== TICKET QUEUE & HISTORICAL PRECEDENTS ===
{ticket_history}

=== RESPONSE FORMAT ===
Always structure your response clearly as:
- **Assessment**: Analysis of the issue & category
- **Decision**: Either **[RESOLVE DIRECTLY]** or **[ROUTE TO HUMAN: <Target Team>]**
- **Action**: Resolution steps provided or routing action taken
- **Next Steps**: What the employee or human assignee must do next
- **KB / Precedent Reference**: Applicable KB article(s) (e.g. KB-01) or Ticket Precedent (e.g. TK-1050)

Be concise, helpful, and strictly policy-compliant."""


def get_request_resolution(req_id: str) -> dict:
    """Get AI-generated resolution for a specific employee request."""
    req = next((r for r in EMPLOYEE_REQUESTS if r["id"] == req_id), None)
    if not req:
        return {"error": "Request not found"}
    return req


def format_kb_for_context() -> str:
    """Format all KB articles as context string."""
    return "\n\n".join([
        f"**{kid} — {v['title']}**\n{v['content']}"
        for kid, v in KNOWLEDGE_BASE.items()
    ])
